apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-whoami
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: dev
    repoURL: 'https://github.com/parthivrmenon/whoami-argocd.git'
    targetRevision: HEAD
  sources: []
  project: dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true